I0328 21:20:59.518452 25101 launcher.cpp:341] ExecutorLauncher::setupEnvironment
I0328 21:20:59.518580 25101 launcher.cpp:346] ExecutorLauncher::setupEnvironment: MESOS_DIRECTORY: /media/LinuxShare2/mesos/work/slaves/201203282053-0-0/frameworks/201203282053-0-0010/executors/default/runs/0
I0328 21:20:59.519002 25101 launcher.cpp:348] ExecutorLauncher::setupEnvironment: MESOS_SLAVE_PID: slave@192.168.1.64:59679
I0328 21:20:59.519393 25101 launcher.cpp:350] ExecutorLauncher::setupEnvironment: MESOS_FRAMEWORK_ID: 201203282053-0-0010
I0328 21:20:59.519583 25101 launcher.cpp:352] ExecutorLauncher::setupEnvironment: MESOS_EXECUTOR_ID: default
I0328 21:20:59.519815 25101 launcher.cpp:360] ExecutorLauncher::setupEnvironment: MESOS_HOME: /media/LinuxShare2/mesos
12/03/28 21:21:00 INFO spark.Executor: Running task ID 0
12/03/28 21:21:00 INFO spark.Executor: Running task ID 3
12/03/28 21:21:00 INFO spark.Executor: Running task ID 2
12/03/28 21:21:00 INFO spark.Executor: Running task ID 1
java.io.IOException: Call to azad/192.168.1.64:54310 failed on local exception: java.io.EOFException
	at org.apache.hadoop.ipc.Client.wrapException(Client.java:775)
	at org.apache.hadoop.ipc.Client.call(Client.java:743)
	at org.apache.hadoop.ipc.RPC$Invoker.invoke(RPC.java:220)
	at $Proxy0.getProtocolVersion(Unknown Source)
	at org.apache.hadoop.ipc.RPC.getProxy(RPC.java:359)
	at org.apache.hadoop.hdfs.DFSClient.createRPCNamenode(DFSClient.java:106)
	at org.apache.hadoop.hdfs.DFSClient.<init>(DFSClient.java:207)
	at org.apache.hadoop.hdfs.DFSClient.<init>(DFSClient.java:170)
	at org.apache.hadoop.hdfs.DistributedFileSystem.initialize(DistributedFileSystem.java:82)
	at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:1378)
	at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:66)
	at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:1390)
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:196)
	at org.apache.hadoop.fs.Path.getFileSystem(Path.java:175)
	at com.virkaz.star.hadoopio.PipesBinaryMatrixRecordReader.next(PipesBinaryMatrixRecordReader.java:182)
	at com.virkaz.star.hadoopio.PipesBinaryMatrixRecordReader.next(PipesBinaryMatrixRecordReader.java:27)
	at spark.HadoopRDD$$anon$1.hasNext(HadoopRDD.scala:81)
	at scala.collection.Iterator$$anon$19.hasNext(Iterator.scala:334)
	at spark.RDD$$anonfun$count$1.apply(RDD.scala:219)
	at spark.RDD$$anonfun$count$1.apply(RDD.scala:217)
	at spark.SparkContext$$anonfun$runJob$3.apply(SparkContext.scala:266)
	at spark.SparkContext$$anonfun$runJob$3.apply(SparkContext.scala:266)
	at spark.ResultTask.run(ResultTask.scala:10)
	at spark.Executor$TaskRunner.run(Executor.scala:71)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
	at java.lang.Thread.run(Thread.java:679)
Caused by: java.io.EOFException
	at java.io.DataInputStream.readInt(DataInputStream.java:392)
	at org.apache.hadoop.ipc.Client$Connection.receiveResponse(Client.java:501)
	at org.apache.hadoop.ipc.Client$Connection.run(Client.java:446)
12/03/28 21:21:00 INFO spark.Executor: Finished task ID 1
java.io.IOException: Call to azad/192.168.1.64:54310 failed on local exception: java.io.EOFException
	at org.apache.hadoop.ipc.Client.wrapException(Client.java:775)
	at org.apache.hadoop.ipc.Client.call(Client.java:743)
	at org.apache.hadoop.ipc.RPC$Invoker.invoke(RPC.java:220)
	at $Proxy0.getProtocolVersion(Unknown Source)
	at org.apache.hadoop.ipc.RPC.getProxy(RPC.java:359)
	at org.apache.hadoop.hdfs.DFSClient.createRPCNamenode(DFSClient.java:106)
	at org.apache.hadoop.hdfs.DFSClient.<init>(DFSClient.java:207)
	at org.apache.hadoop.hdfs.DFSClient.<init>(DFSClient.java:170)
	at org.apache.hadoop.hdfs.DistributedFileSystem.initialize(DistributedFileSystem.java:82)
	at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:1378)
	at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:66)
	at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:1390)
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:196)
	at org.apache.hadoop.fs.Path.getFileSystem(Path.java:175)
	at com.virkaz.star.hadoopio.PipesBinaryMatrixRecordReader.next(PipesBinaryMatrixRecordReader.java:182)
	at com.virkaz.star.hadoopio.PipesBinaryMatrixRecordReader.next(PipesBinaryMatrixRecordReader.java:27)
	at spark.HadoopRDD$$anon$1.hasNext(HadoopRDD.scala:81)
	at scala.collection.Iterator$$anon$19.hasNext(Iterator.scala:334)
	at spark.RDD$$anonfun$count$1.apply(RDD.scala:219)
	at spark.RDD$$anonfun$count$1.apply(RDD.scala:217)
	at spark.SparkContext$$anonfun$runJob$3.apply(SparkContext.scala:266)
	at spark.SparkContext$$anonfun$runJob$3.apply(SparkContext.scala:266)
	at spark.ResultTask.run(ResultTask.scala:10)
	at spark.Executor$TaskRunner.run(Executor.scala:71)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
	at java.lang.Thread.run(Thread.java:679)
Caused by: java.io.EOFException
	at java.io.DataInputStream.readInt(DataInputStream.java:392)
	at org.apache.hadoop.ipc.Client$Connection.receiveResponse(Client.java:501)
	at org.apache.hadoop.ipc.Client$Connection.run(Client.java:446)
12/03/28 21:21:00 INFO spark.Executor: Finished task ID 2
12/03/28 21:21:00 INFO spark.Executor: Running task ID 4
12/03/28 21:21:00 INFO spark.Executor: Running task ID 5
java.io.IOException: Call to azad/192.168.1.64:54310 failed on local exception: java.io.EOFException
	at org.apache.hadoop.ipc.Client.wrapException(Client.java:775)
	at org.apache.hadoop.ipc.Client.call(Client.java:743)
	at org.apache.hadoop.ipc.RPC$Invoker.invoke(RPC.java:220)
	at $Proxy0.getProtocolVersion(Unknown Source)
	at org.apache.hadoop.ipc.RPC.getProxy(RPC.java:359)
	at org.apache.hadoop.hdfs.DFSClient.createRPCNamenode(DFSClient.java:106)
	at org.apache.hadoop.hdfs.DFSClient.<init>(DFSClient.java:207)
	at org.apache.hadoop.hdfs.DFSClient.<init>(DFSClient.java:170)
	at org.apache.hadoop.hdfs.DistributedFileSystem.initialize(DistributedFileSystem.java:82)
	at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:1378)
	at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:66)
	at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:1390)
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:196)
	at org.apache.hadoop.fs.Path.getFileSystem(Path.java:175)
	at com.virkaz.star.hadoopio.PipesBinaryMatrixRecordReader.next(PipesBinaryMatrixRecordReader.java:182)
	at com.virkaz.star.hadoopio.PipesBinaryMatrixRecordReader.next(PipesBinaryMatrixRecordReader.java:27)
	at spark.HadoopRDD$$anon$1.hasNext(HadoopRDD.scala:81)
	at scala.collection.Iterator$$anon$19.hasNext(Iterator.scala:334)
	at spark.RDD$$anonfun$count$1.apply(RDD.scala:219)
	at spark.RDD$$anonfun$count$1.apply(RDD.scala:217)
	at spark.SparkContext$$anonfun$runJob$3.apply(SparkContext.scala:266)
	at spark.SparkContext$$anonfun$runJob$3.apply(SparkContext.scala:266)
	at spark.ResultTask.run(ResultTask.scala:10)
	at spark.Executor$TaskRunner.run(Executor.scala:71)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
	at java.lang.Thread.run(Thread.java:679)
Caused by: java.io.EOFException
	at java.io.DataInputStream.readInt(DataInputStream.java:392)
	at org.apache.hadoop.ipc.Client$Connection.receiveResponse(Client.java:501)
	at org.apache.hadoop.ipc.Client$Connection.run(Client.java:446)
12/03/28 21:21:00 INFO spark.Executor: Finished task ID 3
12/03/28 21:21:00 INFO spark.Executor: Running task ID 6
java.io.IOException: Call to azad/192.168.1.64:54310 failed on local exception: java.io.EOFException
	at org.apache.hadoop.ipc.Client.wrapException(Client.java:775)
	at org.apache.hadoop.ipc.Client.call(Client.java:743)
	at org.apache.hadoop.ipc.RPC$Invoker.invoke(RPC.java:220)
	at $Proxy0.getProtocolVersion(Unknown Source)
	at org.apache.hadoop.ipc.RPC.getProxy(RPC.java:359)
	at org.apache.hadoop.hdfs.DFSClient.createRPCNamenode(DFSClient.java:106)
	at org.apache.hadoop.hdfs.DFSClient.<init>(DFSClient.java:207)
	at org.apache.hadoop.hdfs.DFSClient.<init>(DFSClient.java:170)
	at org.apache.hadoop.hdfs.DistributedFileSystem.initialize(DistributedFileSystem.java:82)
	at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:1378)
	at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:66)
	at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:1390)
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:196)
	at org.apache.hadoop.fs.Path.getFileSystem(Path.java:175)
	at com.virkaz.star.hadoopio.PipesBinaryMatrixRecordReader.next(PipesBinaryMatrixRecordReader.java:182)
	at com.virkaz.star.hadoopio.PipesBinaryMatrixRecordReader.next(PipesBinaryMatrixRecordReader.java:27)
	at spark.HadoopRDD$$anon$1.hasNext(HadoopRDD.scala:81)
	at scala.collection.Iterator$$anon$19.hasNext(Iterator.scala:334)
	at spark.RDD$$anonfun$count$1.apply(RDD.scala:219)
	at spark.RDD$$anonfun$count$1.apply(RDD.scala:217)
	at spark.SparkContext$$anonfun$runJob$3.apply(SparkContext.scala:266)
	at spark.SparkContext$$anonfun$runJob$3.apply(SparkContext.scala:266)
	at spark.ResultTask.run(ResultTask.scala:10)
	at spark.Executor$TaskRunner.run(Executor.scala:71)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
	at java.lang.Thread.run(Thread.java:679)
Caused by: java.io.EOFException
	at java.io.DataInputStream.readInt(DataInputStream.java:392)
	at org.apache.hadoop.ipc.Client$Connection.receiveResponse(Client.java:501)
	at org.apache.hadoop.ipc.Client$Connection.run(Client.java:446)
12/03/28 21:21:01 INFO spark.Executor: Finished task ID 0
12/03/28 21:21:01 INFO spark.Executor: Running task ID 7
java.io.IOException: Call to azad/192.168.1.64:54310 failed on local exception: java.io.EOFException
	at org.apache.hadoop.ipc.Client.wrapException(Client.java:775)
	at org.apache.hadoop.ipc.Client.call(Client.java:743)
	at org.apache.hadoop.ipc.RPC$Invoker.invoke(RPC.java:220)
	at $Proxy0.getProtocolVersion(Unknown Source)
	at org.apache.hadoop.ipc.RPC.getProxy(RPC.java:359)
	at org.apache.hadoop.hdfs.DFSClient.createRPCNamenode(DFSClient.java:106)
	at org.apache.hadoop.hdfs.DFSClient.<init>(DFSClient.java:207)
	at org.apache.hadoop.hdfs.DFSClient.<init>(DFSClient.java:170)
	at org.apache.hadoop.hdfs.DistributedFileSystem.initialize(DistributedFileSystem.java:82)
	at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:1378)
	at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:66)
	at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:1390)
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:196)
	at org.apache.hadoop.fs.Path.getFileSystem(Path.java:175)
	at com.virkaz.star.hadoopio.PipesBinaryMatrixRecordReader.next(PipesBinaryMatrixRecordReader.java:182)
	at com.virkaz.star.hadoopio.PipesBinaryMatrixRecordReader.next(PipesBinaryMatrixRecordReader.java:27)
	at spark.HadoopRDD$$anon$1.hasNext(HadoopRDD.scala:81)
	at scala.collection.Iterator$$anon$19.hasNext(Iterator.scala:334)
	at spark.RDD$$anonfun$count$1.apply(RDD.scala:219)
	at spark.RDD$$anonfun$count$1.apply(RDD.scala:217)
	at spark.SparkContext$$anonfun$runJob$3.apply(SparkContext.scala:266)
	at spark.SparkContext$$anonfun$runJob$3.apply(SparkContext.scala:266)
	at spark.ResultTask.run(ResultTask.scala:10)
	at spark.Executor$TaskRunner.run(Executor.scala:71)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
	at java.lang.Thread.run(Thread.java:679)
Caused by: java.io.EOFException
	at java.io.DataInputStream.readInt(DataInputStream.java:392)
	at org.apache.hadoop.ipc.Client$Connection.receiveResponse(Client.java:501)
	at org.apache.hadoop.ipc.Client$Connection.run(Client.java:446)
12/03/28 21:21:01 INFO spark.Executor: Finished task ID 5
java.io.IOException: Call to azad/192.168.1.64:54310 failed on local exception: java.io.EOFException
	at org.apache.hadoop.ipc.Client.wrapException(Client.java:775)
	at org.apache.hadoop.ipc.Client.call(Client.java:743)
	at org.apache.hadoop.ipc.RPC$Invoker.invoke(RPC.java:220)
	at $Proxy0.getProtocolVersion(Unknown Source)
	at org.apache.hadoop.ipc.RPC.getProxy(RPC.java:359)
	at org.apache.hadoop.hdfs.DFSClient.createRPCNamenode(DFSClient.java:106)
	at org.apache.hadoop.hdfs.DFSClient.<init>(DFSClient.java:207)
	at org.apache.hadoop.hdfs.DFSClient.<init>(DFSClient.java:170)
	at org.apache.hadoop.hdfs.DistributedFileSystem.initialize(DistributedFileSystem.java:82)
	at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:1378)
	at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:66)
	at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:1390)
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:196)
	at org.apache.hadoop.fs.Path.getFileSystem(Path.java:175)
	at com.virkaz.star.hadoopio.PipesBinaryMatrixRecordReader.next(PipesBinaryMatrixRecordReader.java:182)
	at com.virkaz.star.hadoopio.PipesBinaryMatrixRecordReader.next(PipesBinaryMatrixRecordReader.java:27)
	at spark.HadoopRDD$$anon$1.hasNext(HadoopRDD.scala:81)
	at scala.collection.Iterator$$anon$19.hasNext(Iterator.scala:334)
	at spark.RDD$$anonfun$count$1.apply(RDD.scala:219)
	at spark.RDD$$anonfun$count$1.apply(RDD.scala:217)
	at spark.SparkContext$$anonfun$runJob$3.apply(SparkContext.scala:266)
	at spark.SparkContext$$anonfun$runJob$3.apply(SparkContext.scala:266)
	at spark.ResultTask.run(ResultTask.scala:10)
	at spark.Executor$TaskRunner.run(Executor.scala:71)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
	at java.lang.Thread.run(Thread.java:679)
Caused by: java.io.EOFException
	at java.io.DataInputStream.readInt(DataInputStream.java:392)
	at org.apache.hadoop.ipc.Client$Connection.receiveResponse(Client.java:501)
	at org.apache.hadoop.ipc.Client$Connection.run(Client.java:446)
12/03/28 21:21:01 INFO spark.Executor: Finished task ID 4
java.io.IOException: Call to azad/192.168.1.64:54310 failed on local exception: java.io.EOFException
	at org.apache.hadoop.ipc.Client.wrapException(Client.java:775)
	at org.apache.hadoop.ipc.Client.call(Client.java:743)
	at org.apache.hadoop.ipc.RPC$Invoker.invoke(RPC.java:220)
	at $Proxy0.getProtocolVersion(Unknown Source)
	at org.apache.hadoop.ipc.RPC.getProxy(RPC.java:359)
	at org.apache.hadoop.hdfs.DFSClient.createRPCNamenode(DFSClient.java:106)
	at org.apache.hadoop.hdfs.DFSClient.<init>(DFSClient.java:207)
	at org.apache.hadoop.hdfs.DFSClient.<init>(DFSClient.java:170)
	at org.apache.hadoop.hdfs.DistributedFileSystem.initialize(DistributedFileSystem.java:82)
	at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:1378)
	at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:66)
	at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:1390)
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:196)
	at org.apache.hadoop.fs.Path.getFileSystem(Path.java:175)
	at com.virkaz.star.hadoopio.PipesBinaryMatrixRecordReader.next(PipesBinaryMatrixRecordReader.java:182)
	at com.virkaz.star.hadoopio.PipesBinaryMatrixRecordReader.next(PipesBinaryMatrixRecordReader.java:27)
	at spark.HadoopRDD$$anon$1.hasNext(HadoopRDD.scala:81)
	at scala.collection.Iterator$$anon$19.hasNext(Iterator.scala:334)
	at spark.RDD$$anonfun$count$1.apply(RDD.scala:219)
	at spark.RDD$$anonfun$count$1.apply(RDD.scala:217)
	at spark.SparkContext$$anonfun$runJob$3.apply(SparkContext.scala:266)
	at spark.SparkContext$$anonfun$runJob$3.apply(SparkContext.scala:266)
	at spark.ResultTask.run(ResultTask.scala:10)
	at spark.Executor$TaskRunner.run(Executor.scala:71)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
	at java.lang.Thread.run(Thread.java:679)
Caused by: java.io.EOFException
	at java.io.DataInputStream.readInt(DataInputStream.java:392)
	at org.apache.hadoop.ipc.Client$Connection.receiveResponse(Client.java:501)
	at org.apache.hadoop.ipc.Client$Connection.run(Client.java:446)
12/03/28 21:21:01 INFO spark.Executor: Finished task ID 6
java.io.IOException: Call to azad/192.168.1.64:54310 failed on local exception: java.io.EOFException
	at org.apache.hadoop.ipc.Client.wrapException(Client.java:775)
	at org.apache.hadoop.ipc.Client.call(Client.java:743)
	at org.apache.hadoop.ipc.RPC$Invoker.invoke(RPC.java:220)
	at $Proxy0.getProtocolVersion(Unknown Source)
	at org.apache.hadoop.ipc.RPC.getProxy(RPC.java:359)
	at org.apache.hadoop.hdfs.DFSClient.createRPCNamenode(DFSClient.java:106)
	at org.apache.hadoop.hdfs.DFSClient.<init>(DFSClient.java:207)
	at org.apache.hadoop.hdfs.DFSClient.<init>(DFSClient.java:170)
	at org.apache.hadoop.hdfs.DistributedFileSystem.initialize(DistributedFileSystem.java:82)
	at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:1378)
	at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:66)
	at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:1390)
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:196)
	at org.apache.hadoop.fs.Path.getFileSystem(Path.java:175)
	at com.virkaz.star.hadoopio.PipesBinaryMatrixRecordReader.next(PipesBinaryMatrixRecordReader.java:182)
	at com.virkaz.star.hadoopio.PipesBinaryMatrixRecordReader.next(PipesBinaryMatrixRecordReader.java:27)
	at spark.HadoopRDD$$anon$1.hasNext(HadoopRDD.scala:81)
	at scala.collection.Iterator$$anon$19.hasNext(Iterator.scala:334)
	at spark.RDD$$anonfun$count$1.apply(RDD.scala:219)
	at spark.RDD$$anonfun$count$1.apply(RDD.scala:217)
	at spark.SparkContext$$anonfun$runJob$3.apply(SparkContext.scala:266)
	at spark.SparkContext$$anonfun$runJob$3.apply(SparkContext.scala:266)
	at spark.ResultTask.run(ResultTask.scala:10)
	at spark.Executor$TaskRunner.run(Executor.scala:71)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
	at java.lang.Thread.run(Thread.java:679)
Caused by: java.io.EOFException
	at java.io.DataInputStream.readInt(DataInputStream.java:392)
	at org.apache.hadoop.ipc.Client$Connection.receiveResponse(Client.java:501)
	at org.apache.hadoop.ipc.Client$Connection.run(Client.java:446)
12/03/28 21:21:01 INFO spark.Executor: Finished task ID 7
12/03/28 21:21:12 INFO spark.Executor: Running task ID 8
12/03/28 21:21:12 INFO spark.Executor: Running task ID 9
12/03/28 21:21:12 INFO spark.Executor: Running task ID 10
12/03/28 21:21:12 INFO spark.Executor: Running task ID 11
12/03/28 21:21:12 INFO spark.Executor: Finished task ID 8
/hadoop-distro/StdInReaderForArray: error while loading shared libraries: libTree.so: cannot open shared object file: No such file or directory
/hadoop-distro/StdInReaderForArray: error while loading shared libraries: libTree.so: cannot open shared object file: No such file or directory
/hadoop-distro/StdInReaderForArray: error while loading shared libraries: libTree.so: cannot open shared object file: No such file or directory
12/03/28 21:21:12 INFO spark.Executor: Finished task ID 9
/hadoop-distro/StdInReaderForArray: error while loading shared libraries: libTree.so: cannot open shared object file: No such file or directory
12/03/28 21:21:12 INFO spark.Executor: Finished task ID 10
12/03/28 21:21:12 INFO spark.Executor: Finished task ID 11
12/03/28 21:21:12 INFO spark.Executor: Running task ID 12
java.io.IOException: Call to azad/192.168.1.64:54310 failed on local exception: java.io.EOFException
	at org.apache.hadoop.ipc.Client.wrapException(Client.java:775)
	at org.apache.hadoop.ipc.Client.call(Client.java:743)
	at org.apache.hadoop.ipc.RPC$Invoker.invoke(RPC.java:220)
	at $Proxy0.getProtocolVersion(Unknown Source)
	at org.apache.hadoop.ipc.RPC.getProxy(RPC.java:359)
	at org.apache.hadoop.hdfs.DFSClient.createRPCNamenode(DFSClient.java:106)
	at org.apache.hadoop.hdfs.DFSClient.<init>(DFSClient.java:207)
	at org.apache.hadoop.hdfs.DFSClient.<init>(DFSClient.java:170)
	at org.apache.hadoop.hdfs.DistributedFileSystem.initialize(DistributedFileSystem.java:82)
	at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:1378)
	at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:66)
	at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:1390)
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:196)
	at org.apache.hadoop.fs.Path.getFileSystem(Path.java:175)
	at com.virkaz.star.hadoopio.PipesBinaryMatrixRecordReader.next(PipesBinaryMatrixRecordReader.java:182)
	at com.virkaz.star.hadoopio.PipesBinaryMatrixRecordReader.next(PipesBinaryMatrixRecordReader.java:27)
	at spark.HadoopRDD$$anon$1.hasNext(HadoopRDD.scala:81)
	at scala.collection.Iterator$$anon$19.hasNext(Iterator.scala:334)
	at scala.collection.Iterator$$anon$19.hasNext(Iterator.scala:334)
	at scala.collection.Iterator$class.foreach(Iterator.scala:660)
	at scala.collection.Iterator$$anon$19.foreach(Iterator.scala:333)
	at spark.PipedRDD$$anon$2.run(PipedRDD.scala:41)
Caused by: java.io.EOFException
	at java.io.DataInputStream.readInt(DataInputStream.java:392)
	at org.apache.hadoop.ipc.Client$Connection.receiveResponse(Client.java:501)
	at org.apache.hadoop.ipc.Client$Connection.run(Client.java:446)
java.io.IOException: Call to azad/192.168.1.64:54310 failed on local exception: java.io.EOFException
	at org.apache.hadoop.ipc.Client.wrapException(Client.java:775)
	at org.apache.hadoop.ipc.Client.call(Client.java:743)
	at org.apache.hadoop.ipc.RPC$Invoker.invoke(RPC.java:220)
	at $Proxy0.getProtocolVersion(Unknown Source)
	at org.apache.hadoop.ipc.RPC.getProxy(RPC.java:359)
	at org.apache.hadoop.hdfs.DFSClient.createRPCNamenode(DFSClient.java:106)
	at org.apache.hadoop.hdfs.DFSClient.<init>(DFSClient.java:207)
	at org.apache.hadoop.hdfs.DFSClient.<init>(DFSClient.java:170)
	at org.apache.hadoop.hdfs.DistributedFileSystem.initialize(DistributedFileSystem.java:82)
	at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:1378)
	at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:66)
	at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:1390)
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:196)
	at org.apache.hadoop.fs.Path.getFileSystem(Path.java:175)
	at com.virkaz.star.hadoopio.PipesBinaryMatrixRecordReader.next(PipesBinaryMatrixRecordReader.java:182)
	at com.virkaz.star.hadoopio.PipesBinaryMatrixRecordReader.next(PipesBinaryMatrixRecordReader.java:27)
	at spark.HadoopRDD$$anon$1.hasNext(HadoopRDD.scala:81)
	at scala.collection.Iterator$$anon$19.hasNext(Iterator.scala:334)
	at scala.collection.Iterator$$anon$19.hasNext(Iterator.scala:334)
	at scala.collection.Iterator$class.foreach(Iterator.scala:660)
	at scala.collection.Iterator$$anon$19.foreach(Iterator.scala:333)
	at spark.PipedRDD$$anon$2.run(PipedRDD.scala:41)
Caused by: java.io.EOFException
	at java.io.DataInputStream.readInt(DataInputStream.java:392)
	at org.apache.hadoop.ipc.Client$Connection.receiveResponse(Client.java:501)
	at org.apache.hadoop.ipc.Client$Connection.run(Client.java:446)
12/03/28 21:21:12 INFO spark.Executor: Running task ID 13
12/03/28 21:21:12 INFO spark.Executor: Running task ID 14
12/03/28 21:21:12 INFO spark.Executor: Running task ID 15
java.io.IOException: Call to azad/192.168.1.64:54310 failed on local exception: java.io.EOFException
	at org.apache.hadoop.ipc.Client.wrapException(Client.java:775)
	at org.apache.hadoop.ipc.Client.call(Client.java:743)
	at org.apache.hadoop.ipc.RPC$Invoker.invoke(RPC.java:220)
	at $Proxy0.getProtocolVersion(Unknown Source)
	at org.apache.hadoop.ipc.RPC.getProxy(RPC.java:359)
	at org.apache.hadoop.hdfs.DFSClient.createRPCNamenode(DFSClient.java:106)
	at org.apache.hadoop.hdfs.DFSClient.<init>(DFSClient.java:207)
	at org.apache.hadoop.hdfs.DFSClient.<init>(DFSClient.java:170)
	at org.apache.hadoop.hdfs.DistributedFileSystem.initialize(DistributedFileSystem.java:82)
	at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:1378)
	at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:66)
	at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:1390)
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:196)
	at org.apache.hadoop.fs.Path.getFileSystem(Path.java:175)
	at com.virkaz.star.hadoopio.PipesBinaryMatrixRecordReader.next(PipesBinaryMatrixRecordReader.java:182)
	at com.virkaz.star.hadoopio.PipesBinaryMatrixRecordReader.next(PipesBinaryMatrixRecordReader.java:27)
	at spark.HadoopRDD$$anon$1.hasNext(HadoopRDD.scala:81)
	at scala.collection.Iterator$$anon$19.hasNext(Iterator.scala:334)
	at scala.collection.Iterator$$anon$19.hasNext(Iterator.scala:334)
	at scala.collection.Iterator$class.foreach(Iterator.scala:660)
	at scala.collection.Iterator$$anon$19.foreach(Iterator.scala:333)
	at spark.PipedRDD$$anon$2.run(PipedRDD.scala:41)
Caused by: java.io.EOFException
	at java.io.DataInputStream.readInt(DataInputStream.java:392)
	at org.apache.hadoop.ipc.Client$Connection.receiveResponse(Client.java:501)
	at org.apache.hadoop.ipc.Client$Connection.run(Client.java:446)
java.io.IOException: Call to azad/192.168.1.64:54310 failed on local exception: java.io.EOFException
	at org.apache.hadoop.ipc.Client.wrapException(Client.java:775)
	at org.apache.hadoop.ipc.Client.call(Client.java:743)
	at org.apache.hadoop.ipc.RPC$Invoker.invoke(RPC.java:220)
	at $Proxy0.getProtocolVersion(Unknown Source)
	at org.apache.hadoop.ipc.RPC.getProxy(RPC.java:359)
	at org.apache.hadoop.hdfs.DFSClient.createRPCNamenode(DFSClient.java:106)
	at org.apache.hadoop.hdfs.DFSClient.<init>(DFSClient.java:207)
	at org.apache.hadoop.hdfs.DFSClient.<init>(DFSClient.java:170)
	at org.apache.hadoop.hdfs.DistributedFileSystem.initialize(DistributedFileSystem.java:82)
	at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:1378)
	at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:66)
	at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:1390)
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:196)
	at org.apache.hadoop.fs.Path.getFileSystem(Path.java:175)
	at com.virkaz.star.hadoopio.PipesBinaryMatrixRecordReader.next(PipesBinaryMatrixRecordReader.java:182)
	at com.virkaz.star.hadoopio.PipesBinaryMatrixRecordReader.next(PipesBinaryMatrixRecordReader.java:27)
	at spark.HadoopRDD$$anon$1.hasNext(HadoopRDD.scala:81)
	at scala.collection.Iterator$$anon$19.hasNext(Iterator.scala:334)
	at scala.collection.Iterator$$anon$19.hasNext(Iterator.scala:334)
	at scala.collection.Iterator$class.foreach(Iterator.scala:660)
	at scala.collection.Iterator$$anon$19.foreach(Iterator.scala:333)
	at spark.PipedRDD$$anon$2.run(PipedRDD.scala:41)
Caused by: java.io.EOFException
	at java.io.DataInputStream.readInt(DataInputStream.java:392)
	at org.apache.hadoop.ipc.Client$Connection.receiveResponse(Client.java:501)
	at org.apache.hadoop.ipc.Client$Connection.run(Client.java:446)
/hadoop-distro/StdInReaderForArray: error while loading shared libraries: libTree.so: cannot open shared object file: No such file or directory
12/03/28 21:21:12 INFO spark.Executor: Finished task ID 13
/hadoop-distro/StdInReaderForArray: error while loading shared libraries: libTree.so: cannot open shared object file: No such file or directory
12/03/28 21:21:12 INFO spark.Executor: Finished task ID 12
java.io.IOException: Call to azad/192.168.1.64:54310 failed on local exception: java.io.EOFException
	at org.apache.hadoop.ipc.Client.wrapException(Client.java:775)
	at org.apache.hadoop.ipc.Client.call(Client.java:743)
	at org.apache.hadoop.ipc.RPC$Invoker.invoke(RPC.java:220)
	at $Proxy0.getProtocolVersion(Unknown Source)
	at org.apache.hadoop.ipc.RPC.getProxy(RPC.java:359)
	at org.apache.hadoop.hdfs.DFSClient.createRPCNamenode(DFSClient.java:106)
	at org.apache.hadoop.hdfs.DFSClient.<init>(DFSClient.java:207)
	at org.apache.hadoop.hdfs.DFSClient.<init>(DFSClient.java:170)
	at org.apache.hadoop.hdfs.DistributedFileSystem.initialize(DistributedFileSystem.java:82)
	at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:1378)
	at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:66)
	at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:1390)
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:196)
	at org.apache.hadoop.fs.Path.getFileSystem(Path.java:175)
	at com.virkaz.star.hadoopio.PipesBinaryMatrixRecordReader.next(PipesBinaryMatrixRecordReader.java:182)
	at com.virkaz.star.hadoopio.PipesBinaryMatrixRecordReader.next(PipesBinaryMatrixRecordReader.java:27)
	at spark.HadoopRDD$$anon$1.hasNext(HadoopRDD.scala:81)
	at scala.collection.Iterator$$anon$19.hasNext(Iterator.scala:334)
	at scala.collection.Iterator$$anon$19.hasNext(Iterator.scala:334)
	at scala.collection.Iterator$class.foreach(Iterator.scala:660)
	at scala.collection.Iterator$$anon$19.foreach(Iterator.scala:333)
	at spark.PipedRDD$$anon$2.run(PipedRDD.scala:41)
Caused by: java.io.EOFException
	at java.io.DataInputStream.readInt(DataInputStream.java:392)
	at org.apache.hadoop.ipc.Client$Connection.receiveResponse(Client.java:501)
	at org.apache.hadoop.ipc.Client$Connection.run(Client.java:446)
/hadoop-distro/StdInReaderForArray: error while loading shared libraries: libTree.so: cannot open shared object file: No such file or directory
/hadoop-distro/StdInReaderForArray: error while loading shared libraries: libTree.so: cannot open shared object file: No such file or directory
12/03/28 21:21:12 INFO spark.Executor: Finished task ID 15
12/03/28 21:21:12 INFO spark.Executor: Finished task ID 14
java.io.IOException: Call to azad/192.168.1.64:54310 failed on local exception: java.io.EOFException
	at org.apache.hadoop.ipc.Client.wrapException(Client.java:775)
	at org.apache.hadoop.ipc.Client.call(Client.java:743)
	at org.apache.hadoop.ipc.RPC$Invoker.invoke(RPC.java:220)
	at $Proxy0.getProtocolVersion(Unknown Source)
	at org.apache.hadoop.ipc.RPC.getProxy(RPC.java:359)
	at org.apache.hadoop.hdfs.DFSClient.createRPCNamenode(DFSClient.java:106)
	at org.apache.hadoop.hdfs.DFSClient.<init>(DFSClient.java:207)
	at org.apache.hadoop.hdfs.DFSClient.<init>(DFSClient.java:170)
	at org.apache.hadoop.hdfs.DistributedFileSystem.initialize(DistributedFileSystem.java:82)
	at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:1378)
	at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:66)
	at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:1390)
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:196)
	at org.apache.hadoop.fs.Path.getFileSystem(Path.java:175)
	at com.virkaz.star.hadoopio.PipesBinaryMatrixRecordReader.next(PipesBinaryMatrixRecordReader.java:182)
	at com.virkaz.star.hadoopio.PipesBinaryMatrixRecordReader.next(PipesBinaryMatrixRecordReader.java:27)
	at spark.HadoopRDD$$anon$1.hasNext(HadoopRDD.scala:81)
	at scala.collection.Iterator$$anon$19.hasNext(Iterator.scala:334)
	at scala.collection.Iterator$$anon$19.hasNext(Iterator.scala:334)
	at scala.collection.Iterator$class.foreach(Iterator.scala:660)
	at scala.collection.Iterator$$anon$19.foreach(Iterator.scala:333)
	at spark.PipedRDD$$anon$2.run(PipedRDD.scala:41)
Caused by: java.io.EOFException
	at java.io.DataInputStream.readInt(DataInputStream.java:392)
	at org.apache.hadoop.ipc.Client$Connection.receiveResponse(Client.java:501)
	at org.apache.hadoop.ipc.Client$Connection.run(Client.java:446)
java.io.IOException: Call to azad/192.168.1.64:54310 failed on local exception: java.io.EOFException
	at org.apache.hadoop.ipc.Client.wrapException(Client.java:775)
	at org.apache.hadoop.ipc.Client.call(Client.java:743)
	at org.apache.hadoop.ipc.RPC$Invoker.invoke(RPC.java:220)
	at $Proxy0.getProtocolVersion(Unknown Source)
	at org.apache.hadoop.ipc.RPC.getProxy(RPC.java:359)
	at org.apache.hadoop.hdfs.DFSClient.createRPCNamenode(DFSClient.java:106)
	at org.apache.hadoop.hdfs.DFSClient.<init>(DFSClient.java:207)
	at org.apache.hadoop.hdfs.DFSClient.<init>(DFSClient.java:170)
	at org.apache.hadoop.hdfs.DistributedFileSystem.initialize(DistributedFileSystem.java:82)
	at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:1378)
	at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:66)
	at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:1390)
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:196)
	at org.apache.hadoop.fs.Path.getFileSystem(Path.java:175)
	at com.virkaz.star.hadoopio.PipesBinaryMatrixRecordReader.next(PipesBinaryMatrixRecordReader.java:182)
	at com.virkaz.star.hadoopio.PipesBinaryMatrixRecordReader.next(PipesBinaryMatrixRecordReader.java:27)
	at spark.HadoopRDD$$anon$1.hasNext(HadoopRDD.scala:81)
	at scala.collection.Iterator$$anon$19.hasNext(Iterator.scala:334)
	at scala.collection.Iterator$$anon$19.hasNext(Iterator.scala:334)
	at scala.collection.Iterator$class.foreach(Iterator.scala:660)
	at scala.collection.Iterator$$anon$19.foreach(Iterator.scala:333)
	at spark.PipedRDD$$anon$2.run(PipedRDD.scala:41)
Caused by: java.io.EOFException
	at java.io.DataInputStream.readInt(DataInputStream.java:392)
	at org.apache.hadoop.ipc.Client$Connection.receiveResponse(Client.java:501)
	at org.apache.hadoop.ipc.Client$Connection.run(Client.java:446)
java.io.IOException: Call to azad/192.168.1.64:54310 failed on local exception: java.io.EOFException
	at org.apache.hadoop.ipc.Client.wrapException(Client.java:775)
	at org.apache.hadoop.ipc.Client.call(Client.java:743)
	at org.apache.hadoop.ipc.RPC$Invoker.invoke(RPC.java:220)
	at $Proxy0.getProtocolVersion(Unknown Source)
	at org.apache.hadoop.ipc.RPC.getProxy(RPC.java:359)
	at org.apache.hadoop.hdfs.DFSClient.createRPCNamenode(DFSClient.java:106)
	at org.apache.hadoop.hdfs.DFSClient.<init>(DFSClient.java:207)
	at org.apache.hadoop.hdfs.DFSClient.<init>(DFSClient.java:170)
	at org.apache.hadoop.hdfs.DistributedFileSystem.initialize(DistributedFileSystem.java:82)
	at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:1378)
	at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:66)
	at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:1390)
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:196)
	at org.apache.hadoop.fs.Path.getFileSystem(Path.java:175)
	at com.virkaz.star.hadoopio.PipesBinaryMatrixRecordReader.next(PipesBinaryMatrixRecordReader.java:182)
	at com.virkaz.star.hadoopio.PipesBinaryMatrixRecordReader.next(PipesBinaryMatrixRecordReader.java:27)
	at spark.HadoopRDD$$anon$1.hasNext(HadoopRDD.scala:81)
	at scala.collection.Iterator$$anon$19.hasNext(Iterator.scala:334)
	at scala.collection.Iterator$$anon$19.hasNext(Iterator.scala:334)
	at scala.collection.Iterator$class.foreach(Iterator.scala:660)
	at scala.collection.Iterator$$anon$19.foreach(Iterator.scala:333)
	at spark.PipedRDD$$anon$2.run(PipedRDD.scala:41)
Caused by: java.io.EOFException
	at java.io.DataInputStream.readInt(DataInputStream.java:392)
	at org.apache.hadoop.ipc.Client$Connection.receiveResponse(Client.java:501)
	at org.apache.hadoop.ipc.Client$Connection.run(Client.java:446)
12/03/28 21:21:14 INFO spark.Executor: Running task ID 16
12/03/28 21:21:14 INFO spark.Executor: Running task ID 17
12/03/28 21:21:14 INFO spark.Executor: Running task ID 18
12/03/28 21:21:14 INFO spark.Executor: Running task ID 19
/hadoop-distro/StdInReaderForArray: error while loading shared libraries: libTree.so: cannot open shared object file: No such file or directory
/hadoop-distro/StdInReaderForArray: error while loading shared libraries: libTree.so: cannot open shared object file: No such file or directory
/hadoop-distro/StdInReaderForArray: error while loading shared libraries: libTree.so: cannot open shared object file: No such file or directory
12/03/28 21:21:14 INFO spark.Executor: Finished task ID 16
12/03/28 21:21:14 INFO spark.Executor: Finished task ID 19
12/03/28 21:21:14 INFO spark.Executor: Finished task ID 18
/hadoop-distro/StdInReaderForArray: error while loading shared libraries: libTree.so: cannot open shared object file: No such file or directory
12/03/28 21:21:14 INFO spark.Executor: Finished task ID 17
java.io.IOException: Call to azad/192.168.1.64:54310 failed on local exception: java.io.EOFException
	at org.apache.hadoop.ipc.Client.wrapException(Client.java:775)
	at org.apache.hadoop.ipc.Client.call(Client.java:743)
	at org.apache.hadoop.ipc.RPC$Invoker.invoke(RPC.java:220)
	at $Proxy0.getProtocolVersion(Unknown Source)
	at org.apache.hadoop.ipc.RPC.getProxy(RPC.java:359)
	at org.apache.hadoop.hdfs.DFSClient.createRPCNamenode(DFSClient.java:106)
	at org.apache.hadoop.hdfs.DFSClient.<init>(DFSClient.java:207)
	at org.apache.hadoop.hdfs.DFSClient.<init>(DFSClient.java:170)
	at org.apache.hadoop.hdfs.DistributedFileSystem.initialize(DistributedFileSystem.java:82)
	at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:1378)
	at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:66)
	at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:1390)
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:196)
	at org.apache.hadoop.fs.Path.getFileSystem(Path.java:175)
	at com.virkaz.star.hadoopio.PipesBinaryMatrixRecordReader.next(PipesBinaryMatrixRecordReader.java:182)
	at com.virkaz.star.hadoopio.PipesBinaryMatrixRecordReader.next(PipesBinaryMatrixRecordReader.java:27)
	at spark.HadoopRDD$$anon$1.hasNext(HadoopRDD.scala:81)
	at scala.collection.Iterator$$anon$19.hasNext(Iterator.scala:334)
	at scala.collection.Iterator$$anon$19.hasNext(Iterator.scala:334)
	at scala.collection.Iterator$class.foreach(Iterator.scala:660)
	at scala.collection.Iterator$$anon$19.foreach(Iterator.scala:333)
	at spark.PipedRDD$$anon$2.run(PipedRDD.scala:41)
Caused by: java.io.EOFException
	at java.io.DataInputStream.readInt(DataInputStream.java:392)
	at org.apache.hadoop.ipc.Client$Connection.receiveResponse(Client.java:501)
	at org.apache.hadoop.ipc.Client$Connection.run(Client.java:446)
12/03/28 21:21:14 INFO spark.Executor: Running task ID 20
java.io.IOException: Call to azad/192.168.1.64:54310 failed on local exception: java.io.EOFException
	at org.apache.hadoop.ipc.Client.wrapException(Client.java:775)
	at org.apache.hadoop.ipc.Client.call(Client.java:743)
	at org.apache.hadoop.ipc.RPC$Invoker.invoke(RPC.java:220)
	at $Proxy0.getProtocolVersion(Unknown Source)
	at org.apache.hadoop.ipc.RPC.getProxy(RPC.java:359)
	at org.apache.hadoop.hdfs.DFSClient.createRPCNamenode(DFSClient.java:106)
	at org.apache.hadoop.hdfs.DFSClient.<init>(DFSClient.java:207)
	at org.apache.hadoop.hdfs.DFSClient.<init>(DFSClient.java:170)
	at org.apache.hadoop.hdfs.DistributedFileSystem.initialize(DistributedFileSystem.java:82)
	at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:1378)
	at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:66)
	at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:1390)
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:196)
	at org.apache.hadoop.fs.Path.getFileSystem(Path.java:175)
	at com.virkaz.star.hadoopio.PipesBinaryMatrixRecordReader.next(PipesBinaryMatrixRecordReader.java:182)
	at com.virkaz.star.hadoopio.PipesBinaryMatrixRecordReader.next(PipesBinaryMatrixRecordReader.java:27)
	at spark.HadoopRDD$$anon$1.hasNext(HadoopRDD.scala:81)
	at scala.collection.Iterator$$anon$19.hasNext(Iterator.scala:334)
	at scala.collection.Iterator$$anon$19.hasNext(Iterator.scala:334)
	at scala.collection.Iterator$class.foreach(Iterator.scala:660)
	at scala.collection.Iterator$$anon$19.foreach(Iterator.scala:333)
	at spark.PipedRDD$$anon$2.run(PipedRDD.scala:41)
Caused by: java.io.EOFException
	at java.io.DataInputStream.readInt(DataInputStream.java:392)
	at org.apache.hadoop.ipc.Client$Connection.receiveResponse(Client.java:501)
	at org.apache.hadoop.ipc.Client$Connection.run(Client.java:446)
12/03/28 21:21:14 INFO spark.Executor: Running task ID 21
12/03/28 21:21:14 INFO spark.Executor: Running task ID 22
12/03/28 21:21:14 INFO spark.Executor: Running task ID 23
java.io.IOException: Call to azad/192.168.1.64:54310 failed on local exception: java.io.EOFException
	at org.apache.hadoop.ipc.Client.wrapException(Client.java:775)
	at org.apache.hadoop.ipc.Client.call(Client.java:743)
	at org.apache.hadoop.ipc.RPC$Invoker.invoke(RPC.java:220)
	at $Proxy0.getProtocolVersion(Unknown Source)
	at org.apache.hadoop.ipc.RPC.getProxy(RPC.java:359)
	at org.apache.hadoop.hdfs.DFSClient.createRPCNamenode(DFSClient.java:106)
	at org.apache.hadoop.hdfs.DFSClient.<init>(DFSClient.java:207)
	at org.apache.hadoop.hdfs.DFSClient.<init>(DFSClient.java:170)
	at org.apache.hadoop.hdfs.DistributedFileSystem.initialize(DistributedFileSystem.java:82)
	at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:1378)
	at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:66)
	at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:1390)
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:196)
	at org.apache.hadoop.fs.Path.getFileSystem(Path.java:175)
	at com.virkaz.star.hadoopio.PipesBinaryMatrixRecordReader.next(PipesBinaryMatrixRecordReader.java:182)
	at com.virkaz.star.hadoopio.PipesBinaryMatrixRecordReader.next(PipesBinaryMatrixRecordReader.java:27)
	at spark.HadoopRDD$$anon$1.hasNext(HadoopRDD.scala:81)
	at scala.collection.Iterator$$anon$19.hasNext(Iterator.scala:334)
	at scala.collection.Iterator$$anon$19.hasNext(Iterator.scala:334)
	at scala.collection.Iterator$class.foreach(Iterator.scala:660)
	at scala.collection.Iterator$$anon$19.foreach(Iterator.scala:333)
	at spark.PipedRDD$$anon$2.run(PipedRDD.scala:41)
Caused by: java.io.EOFException
	at java.io.DataInputStream.readInt(DataInputStream.java:392)
	at org.apache.hadoop.ipc.Client$Connection.receiveResponse(Client.java:501)
	at org.apache.hadoop.ipc.Client$Connection.run(Client.java:446)
java.io.IOException: Call to azad/192.168.1.64:54310 failed on local exception: java.io.EOFException
	at org.apache.hadoop.ipc.Client.wrapException(Client.java:775)
	at org.apache.hadoop.ipc.Client.call(Client.java:743)
	at org.apache.hadoop.ipc.RPC$Invoker.invoke(RPC.java:220)
	at $Proxy0.getProtocolVersion(Unknown Source)
	at org.apache.hadoop.ipc.RPC.getProxy(RPC.java:359)
	at org.apache.hadoop.hdfs.DFSClient.createRPCNamenode(DFSClient.java:106)
	at org.apache.hadoop.hdfs.DFSClient.<init>(DFSClient.java:207)
	at org.apache.hadoop.hdfs.DFSClient.<init>(DFSClient.java:170)
	at org.apache.hadoop.hdfs.DistributedFileSystem.initialize(DistributedFileSystem.java:82)
	at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:1378)
	at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:66)
	at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:1390)
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:196)
	at org.apache.hadoop.fs.Path.getFileSystem(Path.java:175)
	at com.virkaz.star.hadoopio.PipesBinaryMatrixRecordReader.next(PipesBinaryMatrixRecordReader.java:182)
	at com.virkaz.star.hadoopio.PipesBinaryMatrixRecordReader.next(PipesBinaryMatrixRecordReader.java:27)
	at spark.HadoopRDD$$anon$1.hasNext(HadoopRDD.scala:81)
	at scala.collection.Iterator$$anon$19.hasNext(Iterator.scala:334)
	at scala.collection.Iterator$$anon$19.hasNext(Iterator.scala:334)
	at scala.collection.Iterator$class.foreach(Iterator.scala:660)
	at scala.collection.Iterator$$anon$19.foreach(Iterator.scala:333)
	at spark.PipedRDD$$anon$2.run(PipedRDD.scala:41)
Caused by: java.io.EOFException
	at java.io.DataInputStream.readInt(DataInputStream.java:392)
	at org.apache.hadoop.ipc.Client$Connection.receiveResponse(Client.java:501)
	at org.apache.hadoop.ipc.Client$Connection.run(Client.java:446)
/hadoop-distro/StdInReaderForArray: error while loading shared libraries: libTree.so: cannot open shared object file: No such file or directory
12/03/28 21:21:14 INFO spark.Executor: Finished task ID 20
/hadoop-distro/StdInReaderForArray: error while loading shared libraries: libTree.so: cannot open shared object file: No such file or directory
12/03/28 21:21:14 INFO spark.Executor: Finished task ID 23
java.io.IOException: Call to azad/192.168.1.64:54310 failed on local exception: java.io.EOFException
	at org.apache.hadoop.ipc.Client.wrapException(Client.java:775)
	at org.apache.hadoop.ipc.Client.call(Client.java:743)
	at org.apache.hadoop.ipc.RPC$Invoker.invoke(RPC.java:220)
	at $Proxy0.getProtocolVersion(Unknown Source)
	at org.apache.hadoop.ipc.RPC.getProxy(RPC.java:359)
	at org.apache.hadoop.hdfs.DFSClient.createRPCNamenode(DFSClient.java:106)
	at org.apache.hadoop.hdfs.DFSClient.<init>(DFSClient.java:207)
	at org.apache.hadoop.hdfs.DFSClient.<init>(DFSClient.java:170)
	at org.apache.hadoop.hdfs.DistributedFileSystem.initialize(DistributedFileSystem.java:82)
	at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:1378)
	at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:66)
	at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:1390)
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:196)
	at org.apache.hadoop.fs.Path.getFileSystem(Path.java:175)
	at com.virkaz.star.hadoopio.PipesBinaryMatrixRecordReader.next(PipesBinaryMatrixRecordReader.java:182)
	at com.virkaz.star.hadoopio.PipesBinaryMatrixRecordReader.next(PipesBinaryMatrixRecordReader.java:27)
	at spark.HadoopRDD$$anon$1.hasNext(HadoopRDD.scala:81)
	at scala.collection.Iterator$$anon$19.hasNext(Iterator.scala:334)
	at scala.collection.Iterator$$anon$19.hasNext(Iterator.scala:334)
	at scala.collection.Iterator$class.foreach(Iterator.scala:660)
	at scala.collection.Iterator$$anon$19.foreach(Iterator.scala:333)
	at spark.PipedRDD$$anon$2.run(PipedRDD.scala:41)
Caused by: java.io.EOFException
	at java.io.DataInputStream.readInt(DataInputStream.java:392)
	at org.apache.hadoop.ipc.Client$Connection.receiveResponse(Client.java:501)
	at org.apache.hadoop.ipc.Client$Connection.run(Client.java:446)
java.io.IOException: Call to azad/192.168.1.64:54310 failed on local exception: java.io.EOFException
	at org.apache.hadoop.ipc.Client.wrapException(Client.java:775)
	at org.apache.hadoop.ipc.Client.call(Client.java:743)
	at org.apache.hadoop.ipc.RPC$Invoker.invoke(RPC.java:220)
	at $Proxy0.getProtocolVersion(Unknown Source)
	at org.apache.hadoop.ipc.RPC.getProxy(RPC.java:359)
	at org.apache.hadoop.hdfs.DFSClient.createRPCNamenode(DFSClient.java:106)
	at org.apache.hadoop.hdfs.DFSClient.<init>(DFSClient.java:207)
	at org.apache.hadoop.hdfs.DFSClient.<init>(DFSClient.java:170)
	at org.apache.hadoop.hdfs.DistributedFileSystem.initialize(DistributedFileSystem.java:82)
	at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:1378)
	at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:66)
	at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:1390)
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:196)
	at org.apache.hadoop.fs.Path.getFileSystem(Path.java:175)
	at com.virkaz.star.hadoopio.PipesBinaryMatrixRecordReader.next(PipesBinaryMatrixRecordReader.java:182)
	at com.virkaz.star.hadoopio.PipesBinaryMatrixRecordReader.next(PipesBinaryMatrixRecordReader.java:27)
	at spark.HadoopRDD$$anon$1.hasNext(HadoopRDD.scala:81)
	at scala.collection.Iterator$$anon$19.hasNext(Iterator.scala:334)
	at scala.collection.Iterator$$anon$19.hasNext(Iterator.scala:334)
	at scala.collection.Iterator$class.foreach(Iterator.scala:660)
	at scala.collection.Iterator$$anon$19.foreach(Iterator.scala:333)
	at spark.PipedRDD$$anon$2.run(PipedRDD.scala:41)
Caused by: java.io.EOFException
	at java.io.DataInputStream.readInt(DataInputStream.java:392)
	at org.apache.hadoop.ipc.Client$Connection.receiveResponse(Client.java:501)
	at org.apache.hadoop.ipc.Client$Connection.run(Client.java:446)
/hadoop-distro/StdInReaderForArray: error while loading shared libraries: libTree.so: cannot open shared object file: No such file or directory
12/03/28 21:21:14 INFO spark.Executor: Finished task ID 22
/hadoop-distro/StdInReaderForArray: error while loading shared libraries: libTree.so: cannot open shared object file: No such file or directory
12/03/28 21:21:14 INFO spark.Executor: Finished task ID 21
java.io.IOException: Call to azad/192.168.1.64:54310 failed on local exception: java.io.EOFException
	at org.apache.hadoop.ipc.Client.wrapException(Client.java:775)
	at org.apache.hadoop.ipc.Client.call(Client.java:743)
	at org.apache.hadoop.ipc.RPC$Invoker.invoke(RPC.java:220)
	at $Proxy0.getProtocolVersion(Unknown Source)
	at org.apache.hadoop.ipc.RPC.getProxy(RPC.java:359)
	at org.apache.hadoop.hdfs.DFSClient.createRPCNamenode(DFSClient.java:106)
	at org.apache.hadoop.hdfs.DFSClient.<init>(DFSClient.java:207)
	at org.apache.hadoop.hdfs.DFSClient.<init>(DFSClient.java:170)
	at org.apache.hadoop.hdfs.DistributedFileSystem.initialize(DistributedFileSystem.java:82)
	at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:1378)
	at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:66)
	at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:1390)
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:196)
	at org.apache.hadoop.fs.Path.getFileSystem(Path.java:175)
	at com.virkaz.star.hadoopio.PipesBinaryMatrixRecordReader.next(PipesBinaryMatrixRecordReader.java:182)
	at com.virkaz.star.hadoopio.PipesBinaryMatrixRecordReader.next(PipesBinaryMatrixRecordReader.java:27)
	at spark.HadoopRDD$$anon$1.hasNext(HadoopRDD.scala:81)
	at scala.collection.Iterator$$anon$19.hasNext(Iterator.scala:334)
	at scala.collection.Iterator$$anon$19.hasNext(Iterator.scala:334)
	at scala.collection.Iterator$class.foreach(Iterator.scala:660)
	at scala.collection.Iterator$$anon$19.foreach(Iterator.scala:333)
	at spark.PipedRDD$$anon$2.run(PipedRDD.scala:41)
Caused by: java.io.EOFException
	at java.io.DataInputStream.readInt(DataInputStream.java:392)
	at org.apache.hadoop.ipc.Client$Connection.receiveResponse(Client.java:501)
	at org.apache.hadoop.ipc.Client$Connection.run(Client.java:446)
java.io.IOException: Call to azad/192.168.1.64:54310 failed on local exception: java.io.EOFException
	at org.apache.hadoop.ipc.Client.wrapException(Client.java:775)
	at org.apache.hadoop.ipc.Client.call(Client.java:743)
	at org.apache.hadoop.ipc.RPC$Invoker.invoke(RPC.java:220)
	at $Proxy0.getProtocolVersion(Unknown Source)
	at org.apache.hadoop.ipc.RPC.getProxy(RPC.java:359)
	at org.apache.hadoop.hdfs.DFSClient.createRPCNamenode(DFSClient.java:106)
	at org.apache.hadoop.hdfs.DFSClient.<init>(DFSClient.java:207)
	at org.apache.hadoop.hdfs.DFSClient.<init>(DFSClient.java:170)
	at org.apache.hadoop.hdfs.DistributedFileSystem.initialize(DistributedFileSystem.java:82)
	at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:1378)
	at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:66)
	at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:1390)
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:196)
	at org.apache.hadoop.fs.Path.getFileSystem(Path.java:175)
	at com.virkaz.star.hadoopio.PipesBinaryMatrixRecordReader.next(PipesBinaryMatrixRecordReader.java:182)
	at com.virkaz.star.hadoopio.PipesBinaryMatrixRecordReader.next(PipesBinaryMatrixRecordReader.java:27)
	at spark.HadoopRDD$$anon$1.hasNext(HadoopRDD.scala:81)
	at scala.collection.Iterator$$anon$19.hasNext(Iterator.scala:334)
	at scala.collection.Iterator$$anon$19.hasNext(Iterator.scala:334)
	at scala.collection.Iterator$class.foreach(Iterator.scala:660)
	at scala.collection.Iterator$$anon$19.foreach(Iterator.scala:333)
	at spark.PipedRDD$$anon$2.run(PipedRDD.scala:41)
Caused by: java.io.EOFException
	at java.io.DataInputStream.readInt(DataInputStream.java:392)
	at org.apache.hadoop.ipc.Client$Connection.receiveResponse(Client.java:501)
	at org.apache.hadoop.ipc.Client$Connection.run(Client.java:446)
